services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile.development
    container_name: api
    environment:
      DB_HOST: database
      DB_DATABASE: laravel
      DB_USERNAM: root
      DB_PASSWORD: root
    volumes:
      - ./apps/api:/var/www
    depends_on:
      - database
    networks:
      - inner

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.development
    container_name: frontend
    ports:
      - "4200:4200"
    volumes:
      - ./apps/frontend:/app
    command: ./entrypoint.sh
    networks:
      - inner

  edge:
    image: nginx:alpine
    container_name: edge
    ports:
      - "8080:80"
    volumes:
      - ./apps/api:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - inner

  database:
    image: mysql:8
    container_name: database
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: laravel
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - inner

volumes:
  db-data:

networks:
  inner:
    driver: bridge
