services:
  # Laravel (PHP + Composer)
  app:
    build:
      context: ./apps/api
      dockerfile: Dockerfile.development
    container_name: api
    volumes:
      - ./apps/api:/var/www
    depends_on:
      - mysql
    networks:
      - app-network

  # Nginx
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./apps/api:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  # MySQL
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: laravel
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  # Node.js for Vue 3 (Vite dev server)
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.development
    container_name: frontend
    ports:
      - "5173:5173" # Vite default
    volumes:
      - ./apps/frontend:/app
    command: ./entrypoint.sh
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
